before_install:
  # composer configuration
  - export COMPOSER_CACHE_DIR=.composer-cache/
  - composer config github-oauth.github.com $githubToken

#install:

#before_script:

script:
  - ./bin/phpunit -c tests/

#after_script:
